# second,minute,hour
rate_limits:
  - name: prod_api
    hosts:
      - api.jia-huang.com:80
      - api.jia-huang.com:443
    rules:
      - path: /
        total:
          limit_unit: second
          limit_requests: 500
        token:
          limit_unit: second
          limit_requests: 20
        ip:
          limit_unit: second
          limit_requests: 20

      - path: /app-gateway
        total:
          limit_unit: second
          limit_requests: 100
        token:
          limit_unit: second
          limit_requests: 20
        ip:
          limit_unit: second
          limit_requests: 20


  - name: test_api
    hosts:
      - test.api.jia-huang.com:80
      - test.api.jia-huang.com:443
    rules:
      - path: /
        total:
          limit_unit: second
          limit_requests: 100
        token:
          limit_unit: second
          limit_requests: 20
        ip:
          limit_unit: second
          limit_requests: 20
      - path: /f007dev/admin-gateway/pay/error_mapping/
        token:
          limit_unit: minute
          limit_requests: 10






