policies:
  - name: group1
    hosts:
      - test.api.jia-huang.com:80
    paths:
      - /
    limit_unit: minute
    limit_requests: 10
    rules:
      - type: ip
        limit_unit: minute
        limit_requests: 5
      - type: header
        header: "x-token"
        limit_unit: minute
        limit_requests: 2
