apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
data:
  ingressgateway-ratelimit.yaml: |-
    domain: ingressgateway-ratelimit
    descriptors:
{{- range .Values.policies }}
  {{$name := .name }}
  {{$rules := .rules }}
  {{$limit_unit := .limit_unit }}
  {{$limit_requests := .limit_requests }}
  {{- range .paths }}
    {{$path := . }}
      - key: header_match
        value: "{{ $name }}_{{ $path }}"
        rate_limit:
          unit: {{ $limit_unit }}
          requests_per_unit: {{ $limit_requests }}
        descriptors:
      {{- range $rules }}
        {{- if or (eq .type "header")  (eq .type "ip") }}
         {{- if eq .type "header" }}
          - key: "header_{{ .header }}"
            rate_limit:
              unit: {{ .limit_unit }}
              requests_per_unit: {{ .limit_requests }}
         {{- end }}
         {{- if eq .type "ip"}}
          - key: remote_address
            rate_limit:
              unit: {{ .limit_unit }}
              requests_per_unit: {{ .limit_requests }}
          {{- end }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
